### ISSUE TITLE
Add link to JOSS paper somewhere

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/DCISolver.jl#115]
... somewhere more visible than in the CITATION file.

https://joss.theoj.org/papers/10.21105/joss.03991

**Comment by tmigot** [comment]
There is a badge for it in the readme https://joss.theoj.org/papers/10.21105/joss.03991/status.svg

**Comment by tmigot** [comment]
We could add it to the References section in the readme as well.

**Comment by dpo** [comment]
I think that would be useful.
