### ISSUE TITLE
Paper suggestion: fix margins in plots

### ISSUE THREAD

**Issue by odow** [JuliaSmoothOptimizers/DCISolver.jl#70]
You might want to rebuild these plots with slightly larger margins. 

The top of the P in "Proportion" is cut off, so too is the "g" in "log":
<img width="879" alt="image" src="https://user-images.githubusercontent.com/8177701/146090285-f3d00436-8a0e-463a-9cb5-9032797e3cda.png">

Otherwise, nice job. I like the log output from the solver.

**Comment by tmigot** [comment]
Thanks @odow , this is a nice catch. I will open a PR to fix it.

**Comment by odow** [comment]
Related comment: is the x-axis meant to be a log scale? It looks linear...

**Comment by tmigot** [comment]
It is indeed a logarithmic (base 2) scale. For instance, the figure shows that there is one problem for which DCISolver required 2^15=32768 more time than Ipopt, and we can verify it:
```
using Pkg; Pkg.activate(".")
using JLD2, GR, Plots, SolverBenchmark

@load "ipopt_dcildl_82.jld2" stats # the file `ipopt_dcildl_82.jld2` in the paper folder contains a dataframes with the results of the benchmark.
solved(df) = (df.status .== :first_order)

tim_dci = stats[:dcildl][solved(stats[:dcildl]), :elapsed_time]
tim_ipopt = stats[:ipopt][solved(stats[:dcildl]), :elapsed_time]

maximum(tim_dci./tim_ipopt) # returns 32157.21805890401 which is close to 2^15.
```

**Comment by odow** [comment]
Ah okay, that part needs clarifying in the text then. I through you might have done log10(actual/best), but then that was far too long!

Or could you change the plotting to use a log2 axis? It'd be nicer if the x-ticks showed `2^15` etc.

**Comment by tmigot** [comment]
@odow I changed in #73  the xticks to show the log2 basis.
![ipopt_dcildl_82](https://user-images.githubusercontent.com/25304288/147158035-0e1d93cb-cf24-4db0-b6f1-24161eddb2d4.png)
